#!/bin/bash

# @name         upgrade

# @author       Barra Hart

# @description  A Bash script that performs a full clean upgrade on your Linux
#               machine.



clear

# fancy
hname="$(hostname)"

# fancy
echo "---------------------------------------------------------------------"
echo "upgrade"
echo "---------------------------------------------------------------------"
echo "Author: Barra Hart"
echo "Repo: https://github.com/barrahart/linux-life-hacks"
echo "---------------------------------------------------------------------"
echo "Current User: "
echo "$(echo ${USER})"
echo "---------------------------------------------------------------------"
echo "Full system upgrade for ${hname}"
echo "---------------------------------------------------------------------"

echo ""

# fancy
read -p "Press ENTER to continue, or CTRL-C to exit. "

echo ""

echo "---------------------------------------------------------------------"

# fancy
sleep 1

# fancy
echo ""

# apt commands
apt-get clean
apt clean
apt-get update
apt-get upgrade -y
apt-get dist-upgrade -y
apt-get autoremove -y
apt autoremove -y

sleep 1

echo ""

echo "---------------------------------------------------------------------"
echo "Done"
echo "---------------------------------------------------------------------"
