#!/bin/bash


#########################################################################
# Name:         upgrade                                                 #
#                                                                       #
# Author:       Barra Hart                                              #
#                                                                       #
# Repo:         https://github.com/barrahart/linux-life-hacks           #
#                                                                       #
# Description:  A Bash script that performs a full clean upgrade on     #
#               your Linux machine.             				                #
#########################################################################


# fancy
clear

# fancy
echo "---------------------------------------------------------------------"
echo "::::::::::::::::::::::::::::::Upgrade::::::::::::::::::::::::::::::::"
echo "---------------------------------------------------------------------"
echo ""
echo "---------------------------------------------------------------------"
echo ""
echo "Author: Barra Hart"
echo "Repo: https://github.com/barrahart/linux-life-hacks"
echo ""
echo "Full system upgrade for $(echo $(hostname))"
echo ""
echo "---------------------------------------------------------------------"

echo ""

# fancy
read -p "Press ENTER to continue, or CTRL-C to exit. "

echo ""

echo "---------------------------------------------------------------------"

# fancy
echo ""

# apt commands
apt-get clean
apt clean
apt-get update
apt-get upgrade -y
apt-get dist-upgrade -y
apt-get autoremove -y
apt autoremove -y

echo ""

echo "---------------------------------------------------------------------"
echo "Done."
echo "---------------------------------------------------------------------"
